### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by lkl089** [devunt/DFAssist#1]
매칭중 프로그램 켜면 현재 매칭상태 반영안됨

매칭중 초코보 불러낼시 매칭취소 반영안됨

**Comment by lkl089** [comment]
파티원이 매칭걸면
총 0개 임무 매칭중
     <<오류>>
가 출력됨

**Comment by devunt** [comment]
> 매칭중 프로그램 켜면 현재 매칭상태 반영안됨

현재로써는 해결이 힘든 문제입니다.

> 매칭중 초코보 불러낼시 매칭취소 반영안됨

수정되었습니다.

> 파티원이 매칭걸면
> 총 0개 임무 매칭중
> <<오류>>
> 가 출력됨

수정되었습니다.
단, 매칭 큐에 들어가 있지 않을 시 (=인게임에서 대기 시간이 안 뜰시) 대기 시간이 뜨기 전까지는 알 수 없는 임무라고 나옵니다.

**Comment by devunt** [comment]
수정된 사항은 다음 릴리즈에서 배포될 예정입니다.
