### ISSUE TITLE
인스턴스 지역에 진입했을 경우 오버레이를 숨김

### ISSUE THREAD

**Issue by devunt** [devunt/DFAssist#14]
입장했을 경우 오버레이를 숨기고 일반 필드로 나왔을 경우 오버레이를 다시 보여달라는 기능 요청이 있었음

나중에 언젠가 파판을 재결제하면 그 때 구현하기로...

**Comment by laiglinne-ff** [comment]
인스턴스 구역은 ACT 파서에도 구현되어 있던 것 같은데 찾아서 정리해볼까 하다 포기한게 아쉽네용...
디컴파일링 하면 볼수있긴 하지만...

**Comment by devunt** [comment]
메모리 리딩이 제일 쉽긴 할텐데 그건 최대한 피할 생각이고 아마 packet opcode 0x143의 특정 type에 딸려 오던거로 기억하고 있어요. 자세한건 직접 체크해봐야 할 것 같은데 역시 그러려면 파판을 결제해야...

**Comment by laiglinne-ff** [comment]
[https://github.com/laiglinne-ff/DFAssist/blob/8479562068d58c71f2fad78bee2aa9ba0bb3319a/App/Resources/ZoneList.xml](url) 따로 쓰던걸 넣어놓은거긴 한데 참고해서 수정해보도록...하겠습니다

**Comment by laiglinne-ff** [comment]
![image](https://cloud.githubusercontent.com/assets/20029869/17086905/b405e1d8-5238-11e6-90c1-19f8a1945ed0.png)
는... 확인 도중 던전 입장 코드에 사소한 버그가 있는거 같네요... 이프리트 입장도 안했는데 불꽃신의 제단 입장 코드가 동작한걸 보아... 좀더 찾아봐야겠네요

퇴장시 무조건 0이 뜨는데 지역 이동 이전에 코드를 가지고 있어야 할지도...!

**Comment by laiglinne-ff** [comment]
이 버그의 원인은 타인의 이동코드도 같이 잡고있는거 같습니다....ㅋㅋ...ㅋㅋ...ㅋ...ㅋ..

**Comment by devunt** [comment]
https://github.com/devunt/DFAssist/blob/master/App/Network.Analyser.cs#L145 저도 자꾸 오작동해서 넣어놨던 코드를 주석처리 해 뒀던 기억이네요. 뭔가 추가 정보를 담고 있는 다른 필드가 있을 것 같기도...

**Comment by devunt** [comment]
Log.B(data)를 하시면 data를 hexlify해서 출력이 가능하니 어느 비트에서 차이가 발생하는지 확인해보셔도 될 것 같습니당

**Comment by laiglinne-ff** [comment]
찾았습니다. 8~11 (int 인지 uint인지는 모르겠으나) Self 코드가 있고, 40~43에 대상 코드가 있습니다.

두 코드가 같으면 isSelf 이동. 이동 방법 36번 배열이 0C인 경우 퇴장이네요!
![image](https://cloud.githubusercontent.com/assets/20029869/17087123/8cc960ae-523d-11e6-9b17-79d42fbef358.png)

그 외에는

// 01 : NPC를 통한 이동
// 03 : 일반이동
// 04 : 텔레포
// 07 : 데존
// 0E : 도시 내 이동
// 13 : 거주구 이동	

정도.,..?

**Comment by laiglinne-ff** [comment]
![honeycam 2016-07-25 23-19-22](https://cloud.githubusercontent.com/assets/20029869/17104526/4ac84e78-52be-11e6-8dd8-732d45b56ee8.gif)

헛, 옵션 추가만 하면 될 것 같습니다.
