### ISSUE TITLE
만든 사람에 다른 사람들을 추가

### ISSUE THREAD

**Issue by devunt** [devunt/DFAssist#15]
DFAssist의 정보에 있는 만든 사람들 란에 많은 기여를 해 주신 @laiglinne-ff 님을 추가하고자 합니다.

괜찮으시다면 인게임 서버와 닉네임을 알려주세요 :)

**Comment by laiglinne-ff** [comment]
@devunt 앗... 굳이 안적어주셔도... 그냥 알테마 삼하인이라고 적어주세요!
