### ISSUE TITLE
v20160827.1 버그

### ISSUE THREAD

**Issue by StrayCatNero** [devunt/DFAssist#17]
v20160827.1 업뎃 이후 오버레이 에서 <클라이언트 통신 대기중...> 상태에서
클라이언트/게임서버 연결이 됐음에도 불구하고 오버레이가 넘어가지 않는 버그가 있네요.

대신 매칭을 하면 오버레이 색상이 빨간색인 상태에서 매칭 상황은 정상적으로 나옵니다.

로그 입니다.

[21:17:56] 파이널판타지14 프로세스를 찾는 중...
[21:17:56] 파이널판타지14 프로세스가 선택되었습니다: ffxiv_dx11:10116
[21:17:56] N: 시작중...
[21:17:57] N: 게임서버 연결 감지: 192.168.0.100:54768 -> 183.111.189.38:55024
[21:17:57] N: 게임서버 연결 감지: 192.168.0.100:54769 -> 183.111.189.38:55024
[21:17:57] N: 시작됨

**Comment by laiglinne-ff** [comment]
최초로 임무를 한번 이상 매칭하시면 < 매칭중인 임무 없음 >으로 바뀌게끔 되어있습니다.

초기화쪽 코드에 누락이 되었을수도 있겠네요

**Comment by devunt** [comment]
시간 날 때 확인해보겠습니다.

**Comment by devunt** [comment]
아마도 313a54b17eb442c491b558102d7fcbe5cf5de0ab 에서 수정됐을 것 같네요. 무식하긴 하지만...

**Comment by StrayCatNero** [comment]
얼마전 다시 확인 했을때 다시 정상적으로 돌아가더라고요. 간헐적으로 생기는 버그 인듯 합니다.

매칭툴 만들고 관리하시느라 항상 고생이 많으십니다. 꾸벅(_ _)

**Comment by devunt** [comment]
그게 아마 특정 특수한 지역(예: 마을 여관 등) 에서 도우미를 켤 경우 발생하는 문제로 추측하고 있습니다만... 아마 저 수정으로 그것도 고쳐졌을 것 같네요
