### ISSUE TITLE
프로그램 실행시 오류발생

### ISSUE THREAD

**Issue by lkl089** [devunt/DFAssist#2]
![default](https://cloud.githubusercontent.com/assets/20037318/16355269/e537b17c-3aec-11e6-8073-3f8680fc5c3f.PNG)

띄어쓰기가 있는 폴터에서 업데이트 진행시 오류메세지 출력
띄어쓰기가 없는 폴터에서는 업데이트 정상

**Comment by devunt** [comment]
해결되었습니다.
