### ISSUE TITLE
3.1 대응안됨

### ISSUE THREAD

**Issue by RyuaNerin** [devunt/DFAssist#20]

**Comment by devunt** [comment]
3.1에서 몇몇 기능이 동작하지 않는다는 제보는 이미 받았으나 제가 파판을 결제 안 한 관계로 디버깅을 못 해 보고 있습니다 (__)

**Comment by devunt** [comment]
정량제로 긁으려고 했는데 가난해서 낼 돈이 없네요 흑흑

**Comment by RyuaNerin** [comment]
일단 제가 시간나는대로 해보겠습니다
