### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by rkelek** [devunt/DFAssist#26]
dfassist에 매칭이 되면 gcm 기능을 추가 해볼려고 파일을 받아 프로젝트를 열어 일단 솔루션빌드를 해볼려 하니 devunt.snk 파일이 없다고 오류가 나고있네요..
https://drive.google.com/file/d/0Bx9mfGNDy_IaQXN0NjR5aWxWbVU/view?usp=sharing
오류 이미지 입니다.

혹시 괜찮으시다면 오류 원인을 알수있을까요.. c#쪽은 접한지 얼마 안되어 잘 알지 못해 죄송합니다.

**Comment by devunt** [comment]
배포 전 최종 배포 바이너리를 strong name key로 sign하는 과정에 필요한 키가 제게만 있어서 발생하는 문제인데, 일단 로컬에서 개발하실 때는 App 프로젝트 Properties -> Signing -> Sign the assembly의 체크를 해제하시면 됩니다.

![mstsc_2016-10-04_16-53-48](https://cloud.githubusercontent.com/assets/337728/19066219/272480fa-8a53-11e6-9937-c3f51de53a64.png)

**Comment by rkelek** [comment]
감사합니다!
간단한거였군요 덕분에 완성했습니다!
