### ISSUE TITLE
돌발알림 안됨

### ISSUE THREAD

**Issue by daginiel** [devunt/DFAssist#29]
여기저기 해봐도 안되네요...
저만 안되는건지;;

**Comment by devunt** [comment]
돌발을 선택한 뒤 상단 적용 버튼을 누르셨나요?

**Comment by daginiel** [comment]
네... devunt님은 잘 되시나요?

**Comment by devunt** [comment]
최근 빌드와 최근 게임으로 잘 되는데 알림이 안 되시는 돌발명과 지역이 무엇인지 알 수 있을까요?

**Comment by dlunch** [comment]
코드에 있는 돌발 알림 패킷인 op 323, type 116이 서버에서 오지 않네요. 패킷이 바뀐듯 합니다.

**Comment by devunt** [comment]
https://twitter.com/DFAssist/status/797832564555661312 이런 트윗 보면 돌발 알림 제대로 오고 있다고 파악되는데 돌발 알림이 안 오는 돌발명이라든가의 증상을 조금 더 자세히 설명해주시면 문제 해결에 많은 도움이 될 것 같습니다.
