### ISSUE TITLE
임무찾기가 제대로 실행되지 않는 원인을 모르겠습니다;

### ISSUE THREAD

**Issue by pepeholic** [devunt/DFAssist#37]
예전에 쓰던 DFAssist.v20161011.1 버전이 업데이트 된 이후로 특정 임무찾기 (3.3 이후 업데이트 된 던전이나 토벌전) 등에 매칭 되었을 때 이름을 제대로 출력하질 않아 휴지통에 넣고 새 버전으로 아예 깔아봤습니다만 오버레이가 정상적으로 출력되질 않네요... 이전에 쓰던 20161011.1 버전의 경우에도 마찬가지였구요.

이전 버전은 속성에서 보안 - 사용 권한을 "모든 권한" 으로 체크한 뒤에야 오버레이가 정상 작동해서 되는대로 사용했는데 새로 받은 버전은 권한을 모든 권한으로 늘려줘도 매칭중인 임무 없음으로 넘어가질 않습니다; 어떻게 해야될까요? 항상 관리자 권한으로 실행하고 있습니다.

**Comment by devunt** [comment]
혹시 방화벽에 임무찾기도우미가 허용으로 되어 있는지 알 수 있을까요?

**Comment by devunt** [comment]
추가적인 정보가 올 때까지 일단 닫아놓습니다.
