### ISSUE TITLE
전장매칭시 정상작동하지 않습니다.

### ISSUE THREAD

**Issue by TunaNB** [devunt/DFAssist#38]
봉인된바위섬부터 정말 유용하게 쓰고있습니다.
다만 전장매칭시 로그가 정상이 아닌부분이 있습니다.

전장은 쌍사단 불멸대 흑와단이 모두 8명이 모이면 10분동안 인원수를 보고 10분안에 72명이 안모이면 24인 전장이 매칭됩니다.

일단 첫번째 문제는 전장매칭 대기열은 8명이 모이기전에는 매칭도우미에 계속 1/0/0으로 표기된다는것입니다.

[23:19:32] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 1/0, 0/0, 0/0]
[23:20:19] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 1/0, 0/0, 0/0]
[23:23:20] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 1/0, 0/0, 0/0]
[23:26:21] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 1/0, 0/0, 0/0]
[23:29:22] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 1/0, 0/0, 0/0]
[23:30:10] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]

이런식으로 중간에 1/0, 2/0, 1/0 등 인원이 계산되지않다가 8명이모여야 그때서야 대기열이 뜹니다.

때문에 현재 몇명이 부족한지 알수가 없습니다.

두번째 문제는 

[23:32:24] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]
[23:35:24] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]
[23:38:25] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]
[23:41:14] 현재 버전: v20170322.1
[23:41:14] 최신 버전: v20170322.1
[23:41:14] 최신 버전을 이용중입니다
[23:41:15] 최신 임무 데이터 (버전 20170315.1)를 이용중입니다.
[23:41:26] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]
[23:44:27] DFAN: 매칭 상태 업데이트됨 [영광의 평원 (쇄빙전), 1, 2/0, 2/0, 4/0]

이런식으로 쌍사 불멸 흑와단 유저에게 확인해 모두 로그상 8명이 차있으면 10분뒤 매칭이 되어야하는데 매칭이 안됩니다.

아마 제생각에는 8명이 찼다고 올라간후에 다시 매칭을 취소한사람은 계산되지 않고 계속 8명이였던 대기열이 로그에 3분마다 올라오는 것 같습니다. (로그는 3분마다 무조건 올라옵니다)

인원이 빠지면 현재 파티상황을 알수 있게 1~7명 사이의 로그도 볼수 있으면 좋겠습니다.

전장만 관련된 부분이라 귀찮으시겠지만 시간되시면 개선 부탁드립니다.
pvp링쉘에서 정말 잘 쓰고있습니다 ㅠ ㅠ

**Comment by devunt** [comment]
제가 파판에서 pvp를 한번도 안 해 본 유저라서 어떤 식으로 돌아가는지를 잘 모르겠긴 합니다만...
말씀하셨던 1~7명 사이의 정보는 파판 클라이언트에서 보여주는 정보인가요?

**Comment by hibiyasleep** [comment]
파판 클라이언트 쪽에 `0/2 1/2 0/4`같은 정보가 제대로 뜬다면 확실히 DFA 측의 버그일텐데... 한번 확인해 보겠습니다.

**Comment by hibiyasleep** [comment]
![image](https://cloud.githubusercontent.com/assets/5380174/24512381/5de46d9e-15a9-11e7-9f1d-f17d37be1f02.png)

...지금 매칭될 리가 없을 것 같으니 천천히 확인하겠습니다. 저도 PvP를 해 본 적이 없는지라 어떻게 바로 해결할 수가 없네요 ㅠㅠ

참고로 로그에 남는 인원 데이터는 모두 패킷에 남는 그대로 표시됩니다.

확인 필요한 내용
---

- [ ] 대규모 x 3 x 3 (쇄빙전)
- 매칭 대기 중엔 `0/0/1`, 대규모 파티 1개 매칭 시 `2/2/4`로 날아옴
- [ ] 대규모 x 3?
- [ ] 대규모 x 2?
- [ ] 소규모 x 2?

**Comment by TunaNB** [comment]
pvp 매칭은 위에 히비야님 사진처럼 파판클라이언트에서는 인원수가 안나오구 8명이 모이기전에 1~7명의 정보는 매칭도우미에도 안나와서 알수가없습니당..

pvp링크쉘에 흑와단 쇄빙전 매칭중인 사람이 4명이 있을때 매칭도우미에는 4명 모두 직업에 따라서 1/0 0/0 0/0 식으로 나오면 대기열이 안뜨는것으로 보아 4~7명 혹은 8명이 꽉찬 대기열  + 4~7 명이 있구나 하고 추측만 하고있습니다.

**Comment by TunaNB** [comment]
아 참고로 전장은 직업중복제한이없어서 8명이모이면 매칭도우미에 모인 인원직업대로 8인대기열이 뜹니다.
3/0 1/0 4/0 
2/0 0/0 6/0
0/0 8/0 0/0 등등

**Comment by devunt** [comment]
1~7명의 정보가 파판 클라이언트에서도 안 보여주는 정보라면 서버에서도 아예 매칭 인원에 대한 패킷이 안 올 가능성을 배제할 수가 없어서 매칭 도우미에서도 보여줄 수 있다고 확정드릴 수가 없습니다. 허나 기존 매칭과는 다른 아예 다른 패킷 opcode으로 정보가 오고 있었을 가능성도 배제할 수가 없기 때문에... 일단 계속 보고 있긴 하겠습니다.

**Comment by dlunch** [comment]
서버에서 안 보내주는게 맞구요 다른 op도 없습니다. 해결 불가능한 이슈같네요

**Comment by dlunch** [comment]
24명 찬 뒤 10분후 매칭 안되는것 역시 게임 서버쪽 문제입니다.

**Comment by hibiyasleep** [comment]
@dlunch 확인 감사합니다! 시간나는 대로 패치해 보겠습니다.

**Comment by dlunch** [comment]
엥....... 무슨 패치요?

**Comment by hibiyasleep** [comment]
`매칭 중: 1/0 3/0 5/0` 말고 `파티 매칭 대기 중`로 뜬다던가 뭐 그런....

**Comment by dlunch** [comment]
글쿤영

**Comment by devunt** [comment]
이거 해결 된건가요? 역시나 제가 PvP를 안 해서...

**Comment by dlunch** [comment]
@hibiya 님 이슈는 새로 파야할 것 같고 이 이슈는 invalid 같습니다. 서버에서 정보를 안주는거에요

2017년 9월 7일 (목) 오후 2:54, Bae Junehyeon <notifications@github.com>님이 작성:

**Comment by devunt** [comment]
그럼 일단 닫겠습니다!
