### ISSUE TITLE
접속종료후 다른 서버로 접속시 프로그램 작동안함

### ISSUE THREAD

**Issue by lkl089** [devunt/DFAssist#4]
예를들어 리바서버에서 플레이 하다가 접속 종료후 시바서버 캐릭터로 접속하면 
매칭상황 업데이트 안됨 (게임 재시작이 아닌 서버변경)

오류로그는 없음

**Comment by laiglinne-ff** [comment]
@devunt 
Flag 0x011 (FIN) 패킷이 서버로 두번, 클라이언트로 두번 전송됩니다. 
같은 서버로 재접속 (환상약 등)시에도 동일 현상이 발생하고 있습니다.

**Comment by devunt** [comment]
@laiglinne-ff https://github.com/devunt/DFAssist/blob/master/App/Network.cs#L194 이미 지금도 FIN/RST 패킷 처리는 구현되어 있으나 어떤 이유로 제대로 동작이 안 하는 것 같네요. 확인중에 있습니다.

**Comment by laiglinne-ff** [comment]
@devunt 그렇군요 (mm

**Comment by devunt** [comment]
오작동하고 있던 FIN/RST 부분을 해결하긴 했으나 FIN/RST 패킷 등을 이용해서 연결 해제를 즉시 감지해서 표시해주는 기능이 패킷 필터링 성능 저하를 감수할만큼의 실익은 없다고 생각해서 그냥 전체 부분을 주석처리 해 놨습니다.

어차피 30초에 한번씩 현재 서버 연결 목록을 체크하니까 최악의 경우 30초 늦게 연결 해제를 감지하겠지만 전체적인 패킷 필터링 성능 향상을 생각해 보면 나쁘지 않은 결정인 것 같네요 :)
