### ISSUE TITLE
글섭유저입니다

### ISSUE THREAD

**Issue by juno0** [devunt/DFAssist#43]
안녕하세요..
한섭에서 사용해보고 너무 좋아서 글섭에서 사용하는데  안돼더라구요...ㅠㅠ
혹시라도 글섭에서 사용할수 있는방법이 있을까요?.
부탁드려요.. 너무 사용해보고 싶어요..^^

**Comment by Jaehyuk-Lee** [comment]
글섭에서 작동하던데요? 다만 글섭에만 있는 던전에 적절한 정보가 제대로 표기가 안된다는 문제가 있지만, 매칭이 되면 매칭되는 챠킹 소리가 나는 것은 정상 작동합니다.

**Comment by Jaehyuk-Lee** [comment]
아 돌발 문제는 지원이 안되는거죠..

**Comment by Jaehyuk-Lee** [comment]
방금 확인해보니 무작위 임무는 알림이 안오네요

**Comment by Jaehyuk-Lee** [comment]
시스템 소리 백그라운드에서도 들리게 해논거였는데
그걸 이 프로그램이 작동했다고 착각했었나보네요.. 제가

**Comment by devunt** [comment]
글섭 지원 버전이 릴리즈되었습니다.

https://github.com/devunt/DFAssist/releases/tag/v20170904.1
