### ISSUE TITLE
무작위 임무 동시 매칭시 실제 매칭된 전투와 다른 정보가 뜨는 문제

### ISSUE THREAD

**Issue by canasta** [devunt/DFAssist#5]
무작위 전투 매칭 시, 두 개 이상 전투에 인원이 모두 찰 경우 제일 먼저 뜬 전투(유저에게 입장 확인하는 전투)가 아닌 제일 마지막에 인원이 찬 전투(무시되는 전투) 정보가 표시됩니다.
ex: 무작위 토벌로 신청 -> 진 시바 매칭, 입장 선택 창 뜸 -> 동시에 진 라무도 매칭 -> 도우미에는 진 라무 정보 표시

**Comment by devunt** [comment]
임시방편이긴 한데 일단은 해결이 된 것 같네요.
