### ISSUE TITLE
[건의]ARR 고대무기 아니무스 프리셋 기능 추가

### ISSUE THREAD

**Issue by SkynetFactory** [devunt/DFAssist#55]
현재 돌발 체크 기능은 각 돌발별로 하도록 돼있는데

주로 사용하는 용도로 아니무스 돌발 체크 용도로 사용하고 있습니다

아니무스 9 권의 프리셋을 만들어서 빠르게 해당 돌발을 체크할 수 있는 기능이 생겼으면 좋겠습니다

언제나 수고하십니다

**Comment by laiglinne-ff** [comment]
아니무스를 안해봐서... 아니무스 돌발들을 알려주시면 작업해 드립니다

**Comment by devunt** [comment]
@laiglinne-ff https://ffxiv.consolegameswiki.com/wiki/Animus_Zodiac_Weapons/Quest 이런거 참고하면 될 것 같네요

**Comment by SkynetFactory** [comment]
@laiglinne-ff 
불의 서 1 권 | 커르다스 중앙고지 - 기병의 천적 | 외지 라노시아 - 뇌우를 부르는 자 | 검은장막 숲 동부삼림 - 종달새의 지저귐 조우전, 계속되는 종달새의 지저귐   조우전
불의 서 2 권 | 검은장막 숲 북부삼림 - 이크살군 벌채장 강습 작전 | 서부 라노시아 - 남쪽 방파벽 전투: 전력 정찰, 남쪽 방파벽 전투: 주력부대 습격 | 남부 다날란 - 우리는 제2전투대대
불의 서 3 권 | 검은장막 숲 동부삼림 - 무지무지 즐거운 버섯따기 | 모르도나 - 잔인한 악귀 | 남부 다날란 - 운명의 대변인
물의 서 1 권 | 커르다스 중앙고지 - 입 큰 악귀 | 서부 라노시아 - 이국에서 온 괴물 곤충 | 동부 다날란 - 꿈틀꿈틀 도브란
물의 서 2 권 | 검은장막 숲 동부삼림 - 유곡의 약사 | 서부 라노시아 - 북쪽 방파벽 전투: 전력 정찰, 북쪽 방파벽 전투: 주력부대 습격 | 모르도나 - 늪지대의 원혼
물의 서 3 권 | 검은장막 숲 북부삼림 - 유적의 망령기사 | 커르다스 중앙고지 - 후엘록 네 자매 | 북부 다날란 - 무역로 청린수길
바람의 서 1 권 | 검은장막 숲 중부삼림 - 음험한 마물 | 모르도나 - 몰볼, 분노의 대증식 | 고지라노시아 - 수송부대 방어명령
바람의 서 2 권 | 검은장막 숲 남부삼림 - 최후의 멧돼지왕 | 커르다스 중앙고지 - 아유나르트의 의지 | 남부다날란 - 친구와 가족
땅의 서 1권 | 외지 라노시아 - 시굴지 강습작전 | 커르다스 중앙고지 - 설산의 습격자 | 동부 다날란 - 추악한 합성수

목록은 위와 같습니다

**Comment by laiglinne-ff** [comment]
#56

**Comment by devunt** [comment]
머지되었습니다 영문판은 나중에 인터페이스 번역 추가할 때 같이 추가해놓겠습니다
