### ISSUE TITLE
cross-world party 참가 중에는 DFAssist가 꺼집니다.

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [devunt/DFAssist#69]
글로벌 서버에서 cross-world 파티 참가 중일 때 DFAssist가 매칭 중이지 않은 데도 매칭 시작했다고 처리하고 응용 프로그램이 중지됩니다.
![k-004](https://user-images.githubusercontent.com/4695371/29612684-6f84a6a2-883d-11e7-9381-3ee47a9cdef7.jpg)

(들어가자마자 참가 신청 로그가 뜨는 것은 아니고, 조금 있다가 뜹니다. 로그가 뜨자마자 프로그램이 중지되는 것도 아니고 역시 조금 있다가 중지됩니다.)

**Comment by devunt** [comment]
음 cross-world 파티가 뭔지 몰라서 대응하기가 힘드네요

**Comment by Jaehyuk-Lee** [comment]
3.5 패치에 추가되는 데이터센터 내부 인원들간 파티 맺기가 가능한 기능입니다. 한국 서버는 모든 서버가 하나의 데이터센터에 있음.
(현재 한국 서버는 같은 서버에서만 가능)

**Comment by devunt** [comment]
아마 3.5에서 패킷 옵코드가 좀 바뀌는 것 같네요. 작동 중지는 아마 opcode 이상한거 들어온거 처리하다가 out of index가 나는 것 같은데 확인을 좀 더 해 보겠습니다. 조만간 글섭도 시작해봐야겠네요...

**Comment by Jaehyuk-Lee** [comment]
v20170609.1 릴리즈 버전 로그

[15:04:42] DFAN: 매칭 시작됨 (6C) [알 수 없는 임무 (0)]
[15:04:50] 메시지 처리중 에러 발생함: 인덱스가 범위를 벗어났습니다. 인덱스는 음수가 아니어야 하며 컬렉션의 크기보다 작아야 합니다.
매개 변수 이름: startIndex
[15:04:58] DFAN: 매칭 시작됨 (6C) [알 수 없는 임무 (0)]
[15:05:00] DFAN: 매칭 시작됨 (6C) [알 수 없는 임무 (0)]

**Comment by Jaehyuk-Lee** [comment]
일단 cross-world 파티에 참가한 상태이면서, 임무 신청을 하지 않은 상태일 때 나오는 문제이기 때문에 
최대 5개 임무 중에서 첫번째 instance code를 받아오는 곳이 0인지를 보고, 정상적인 임무 신청 상태인지 판단하도록 바꾸겠습니다.

**Comment by devunt** [comment]
#70 에서 해결
