### ISSUE TITLE
Font size problem

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [devunt/DFAssist#71]
from VanillaAphrodite (reddit user)
> Hello, thank you for making this program. I am wondering if there is a way to change the font size in the overlay because all the lines get cut off half way through. Here is a picture: http://imgur.com/a/tMjLO

저는 윈도우 UI 배율 설정 때문에 발생한 문제였는줄 알았는데, 직접 테스트해보니 배율을 바꿔도 옳바른 크기로 나왔습니다. 윈도우 10에서만 멀쩡한걸지도 모르겠는데, 이런 문제가 왜 생기는걸까요?

뭐 특별한 설정 없냐고 물어봤더니, 특별한 UI 설정은 없고, 윈도우 7으로 사용 중이라고 하네요.

잠시 후, 다음과 같은 추가 답변을 받았습니다.

> I completely understand. I found what the problem is, in display settings where you can enlarge fonts I have it at "Medium - 125%", when I switch that to small 100% it displays as it should. I can't change that as my gaming setup is a 52in tv and not being able to read stuff from across the living room for the rest of Windows isn't an option.

윈도우 10에서는 없고 윈도우 7에서 나타나는 문제 같네요. 그 윈도우 UI 배율 설정을 말하는 것 같습니다.

**Comment by devunt** [comment]
9/4 (한섭 3.5 패치 전날) DFAssist 새 버전 릴리즈 계획이니 그 전까지 수정해주시면 같이 포함시켜서 릴리즈하도록 하겠습니다

**Comment by Jaehyuk-Lee** [comment]
Form의 속성 중 AutoScaleMode를 Dpi로 바꾸면 어느 정도 해결됩니다.
![17](https://user-images.githubusercontent.com/4695371/29964120-0a4d0f3c-8f44-11e7-9328-79330ef2f459.png)

하지만 위에서 트위터 기능 영어 설명을 보시면, 글자가 짤립니다.
한글로 보면 상태가 더 심각합니다.

![19](https://user-images.githubusercontent.com/4695371/29964181-364927c4-8f44-11e7-8584-891d3645056c.png)
설명이 짤립니다.

**Comment by Jaehyuk-Lee** [comment]
해결은 했는데... 비주얼 스튜디오에서 자동으로 변환하는 코드 때문에 제가 만지지 않은 부분이 자동으로 바뀌는 문제가 있습니다.
예) 'Dotum' -> '돋움' 변경
이걸 어떻게 고쳐야할지 알아보고 있습니다.

**Comment by Jaehyuk-Lee** [comment]
혹시 폼 디자인 변경할 때 디자이너를 쓰지 않고 코드로 변경해야 하나요??
코드를 디자이너가 마음대로 바꾸는듯 하네요.

[커밋](https://github.com/Jaehyuk-Lee/DFAssist/commit/75c0215432f58f0c4182f7c357632acb4013c36a)

**Comment by devunt** [comment]
커밋할 때 수정된 내용을 전부 다 커밋하는게 아닌 커밋을 하려고 하는 내용(=직접 수정하신 내용)만 포함하시면 될 것 같습니다. 명령줄에서는 `git add -p` 등의 명령을 통해 하실 수 있고, 윈도우에서는 sourcetree 등의 git 프론트엔드 클라이언트를 사용하시면 좀 더 편하게 하실 수 있지 않을까 합니다

**Comment by Jaehyuk-Lee** [comment]
sourcetree를 이용해서 그나마 편하게 커밋할 내용을 골라서 커밋할 수 있었습니다.
하지만 근본적인 원인을 고칠 수 있었으면 하네요. 흐...

**Comment by devunt** [comment]
아마 폰트 이름이 자동으로 윈도우 기본 언어를 따라가는 것 같은데(저는 영문 윈도우를 씁니다) 이걸 vs에서 영어로 강제하는게 가능할지는 잘 모르겠네요

**Comment by devunt** [comment]
#72 머지하고 빌드해보니 ui 아랫쪽이 살짝 잘리는 것 같습니다.

![image](https://user-images.githubusercontent.com/337728/29982288-15d98cb6-8f8c-11e7-933a-892d7822f904.png)

**Comment by devunt** [comment]
#73 에서 해결됨
