### ISSUE TITLE
깃헙 페이지에 언어 선택 추가하기

### ISSUE THREAD

**Issue by devunt** [devunt/DFAssist#76]
다음 릴리즈에 다국어 지원이 추가되는 관계로 깃헙 페이지에도 index / index.en 선택 링크가 필요함

v20170904.1 릴리즈 (#74) 전에 수정 필요

**Comment by Jaehyuk-Lee** [comment]
그냥 `README.md`에 

한국어 설명: https://devunt.github.io/DFAssist
English Description: https://devunt.github.io/DFAssist/index.en

이렇게 쓰면 안되나요?

**Comment by devunt** [comment]
그럼 github.io 홈페이지로 온 외국어 사용자가 원하는 언어 설명으로 갈 방법이 없습니다.

**Comment by Jaehyuk-Lee** [comment]
설명 페이지로 쓰는게 아니라 써놓으신대로 홈페이지처럼 쓰려고 하셨군요.

**Comment by devunt** [comment]
넵 그렇습니다 깃헙쪽은 ui가 불편하기도 하고 초보자 친화적이지 않아서 앞으로는 github.io 쪽 링크만 공유하려고 합니다

**Comment by Jaehyuk-Lee** [comment]
가로 1920 화면
![k-001](https://user-images.githubusercontent.com/4695371/30018556-559bd404-9198-11e7-9037-ab97c99d0c3a.jpg)

모바일 화면
![k-002](https://user-images.githubusercontent.com/4695371/30018557-55c58e2a-9198-11e7-9e4c-1f8e7594de9b.jpg)

이러면 나름 괜찮은 것 같은데 그대로 올릴까요?

**Comment by devunt** [comment]
헛 넵 직접 해 주셨군요 감사합니다 괜찮은 것 같네요!

**Comment by devunt** [comment]
#77 에서 해결됨
