### ISSUE TITLE
기공성 알렉산더 기동편 알수없음

### ISSUE THREAD

**Issue by lkl089** [devunt/DFAssist#8]
기공성 알렉산더 기동편 매칭시 알수없음 출력

**Comment by devunt** [comment]
아직 밖이라 들어가는대로 패치 받고 수정할 예정입니다.
On Tue, Jul 5, 2016 at 19:20 lkl089 <notifications@github.com> wrote:

> 기공성 알렉산더 기동편 매칭시 알수없음 출력
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/devunt/DFAssist/issues/8>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAUnQLjeGgbpyomZvmWfJSnHJ0gQUxMMks5qSi_ngaJpZM4JE-VV>
> .
>
-- 
Sincerely,
June

**Comment by devunt** [comment]
103355e414ecfb53dafb5130c239e6fe22a648c0 에서 @laiglinne-ff 님께서 수고해주셨습니다.
