### ISSUE TITLE
실행 파일 이름이 변경되어 있으면 자동 업데이트가 반복됨

### ISSUE THREAD

**Issue by hibiyasleep** [devunt/DFAssist#80]
취향상(...) PATH에 들어있는 `C:\usr\bin\dfa.exe`로 이름을 바꿔두고 사용했는데, 오늘 ~배그하는 도중~ 자동 업데이트가 뜨더니 업데이트를 반복하기 시작했습니다. 변경된 파일 이름을 감지해서 덮어쓰거나 아예 무시하도록 두면 좋을 듯 합니다.

**Comment by devunt** [comment]
(...) 확인해보겠습니다
배그에 지장을 끼쳐드려 죄송합니다

**Comment by devunt** [comment]
수정되었습니다 (아마?).
