### ISSUE TITLE
매칭된 임무 미리 보기 문제

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [devunt/DFAssist#83]
영어권 커뮤니티에서는 이 기능을 심각하게 바라 보고 있는 사람이 많습니다. 잘 쓰겠다는 사람도 조금 있지만 많은 사람들이 악용의 여지가 있는 기능이라고 안좋게 보고 있습니다. 일부는 RMT나 오토를 쓰는거랑 동급으로 보기도 합니다.(시스템 악용의 가능성이 있다는 점에서)

https://www.reddit.com/r/ffxiv/comments/6y0p41/duty_finderfate_assist_fully_supports_global/
여길 확인하시면 될 겁니다.

이 기능을 지울지 납둘지 결정해야 할 것 같네요.

**Comment by Jaehyuk-Lee** [comment]
한국 서버는 새싹 도와주는데 진짜 많은 사람들이 적극적이지만 글로벌에선 별 관심이 없습니다. 그래서 이 기능이 메인퀘를 진행하는데 방해될 가능성이 글로벌 서버는 더 높죠. (한섭은 그냥 안잡히면 도와달라 하면 금방 끝나지만 글섭은 도와달라고 할만한 곳이 마땅치 않습니다.)

**Comment by devunt** [comment]
한국에서도 몇 번 논란이 됐던 문제인데 (#22, #34) 일단은 경고를 달아두는 정도로 결론이 났었습니다. 제 개인적인 생각은 입장 거부도 시스템 내에 패널티가 있는 한 개인이 알아서 판단할 자율의 영역이라고 보고 있고요.

**Comment by devunt** [comment]
사실 특정 기능의 존재 여부와는 관련 없이 DFAssist는 파판 패킷을 뜯은 순간부터 불법 프로그램인거고 그 시점부터 사용에 대한 모든 책임은 유저가 지고 있습니다. 저라면 따로 대응하지 않고 그냥 각자의 신념에 맞춰서 사용하라고 하고 싶네요. 스레드에 나와있는 것처럼 게임 문화에 영향을 끼칠 만큼 사용 유저가 유의미하게 많을 것 같지도 않고요 (현재 한국 서버에서는 약 300명 가량이 사용중입니다).

**Comment by devunt** [comment]
일단 당장 생각나는건 UI에서 설정 가능한 옵션은 빼 버리고 설정 파일을 수동으로 고쳐야 기능이 활성화되는 방법 정도는 생각해볼 수 있겠는데요...

그리고 어차피 라이센스도 퍼블릭 도메인이라서 저는 아무런 권리를 행사하고 있지 않으니 제 의견과 다르거나 원하시는 분은 포크해서 이름도 새로 짓고 따로 배포하셔도 괜찮습니다.

**Comment by Jaehyuk-Lee** [comment]
그게 경고를 표시하고 프로그램 재시작마다 설정을 다시 해야한다는 점을 알려줬음에도 게임 클라이언트에서 불가능한 것을 외부 프로그램으로 악용할 수 있다는 점 자체만으로도 비난을 하고 있습니다.
가능성이 있는 것 자체가 문제라고 하는거죠.
이 외의 기능은 이미 게임에서 지원하는 기능을 외부 알림으로 확장한 것 뿐이니 그 사람들도 별 문제 없다고 보고 있습니다. 
패킷을 가로채는 행위가 중요한게 아니라 원래 게임에서 불가능한 걸 할 수 있게 해주는게 문제라고 하는거죠.

랜덤 매칭 없이 완전히 구성된 파티로 무작위 던전을 갈 때는 다른 사람들과는 연관이 없으니 이 프로그램이 오히려 유용하게 쓰일 수도 있다는 의견이 있습니다.

파티 매칭으로 랜덤 매칭 없이 무작위 임무 매칭할 때만 매칭된 임무를 보여주는 방법은 어떨까요? - 가능할지는 알아봐야겠지만요.

**Comment by devunt** [comment]
그리고 마찬가지로 스레드에도 있듯이 하기 싫은 임무가 있으면 본인이 패널티를 받으면서 입장 거부하는게 입장하고 대충 대충 하면서 분위기 흐리는 것보단 더 나은 방향인 것 같네요. 주로 프로그램을 쓰는건 매칭이 오래 걸리는 딜러일텐데 딜러 하나 매칭 거부해도 바로 이어서 큐 들어올 딜러는 많습니다.

그리고 한국어일 때는 선택할 수 있게 해 주고 다른 언어일 때는 기능을 없애버리는 것도 좀 웃긴 것 같고요.

뭐 위에도 말했지만 싫으면 안 쓰면 된다고 봅니다.
저도 처음에 이것 저것 만들어서 공개할 때는 최대한 많은 사람들이 제가 만든걸 좋아하고 써 주면 뿌듯하고 반대로 욕하면 상처받고 그랬는데 사실 좀 하다 보니까 뭘 해도 좋아할 사람은 좋아하고 싫어할 사람은 싫어하더라고요. 모두를 맞추는건 불가능하다고 생각해요.

**Comment by Jaehyuk-Lee** [comment]
저도 그 의견이 소수였다면 그냥 납뒀을 텐데 (아마 [안좋다]60:40[좋다] 이었어도 넘어갔을겁니다.)
안좋다는 의견 upvote가 32
좋다는 의견 upvote가 8 이라
그냥 넘어가기가 그렇더군요.

사용하는 사람이 많지 않아서 이게 별 문제가 될건 아니라고 보긴 합니다. 하지만 이 프로그램으로 다른 사람이 영향을 받기는 한다는 것 때문에 반대하는 사람들이 있는 것 같아요. 안쓴다고 될 일이 아니니까요.
