### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by lanceangel** [devunt/DFAssist#87]
possible to add weather?

**Comment by laiglinne-ff** [comment]
It's some difficult. but known field weather add possible.
But why do you need the weather for at F.A.T.E and Duty program?

**Comment by laiglinne-ff** [comment]
@lanceangel 
It's some difficult. but known field weather add possible.
But why do you need the weather for at F.A.T.E and Duty program...?

**Comment by devunt** [comment]
Closing as inactive.
