### ISSUE TITLE
exact duty 

### ISSUE THREAD

**Issue by lanceangel** [devunt/DFAssist#90]
so can't show exact duty anymore?

**Comment by devunt** [comment]
As indicated in the release notes which is written in Korean, there are no spaces to place an option to enable exact matched duty inspector feature.

**Comment by SonicAngel** [comment]
Can we get a version of the program so it can show the exact duty? Or at least be able to access an older version without it selfupdating? Some people are using the DFAssist tool only for that.

**Comment by devunt** [comment]
Then I recommened using [this version](http://www.inven.co.kr/board/ff14/4336/561661) (use the google drive link in the article).
It is a fork of this project for that exact purpose.
Please use it at your own risk.

**Comment by Aida-Enna** [comment]
You say there's "no more space to place an option" - Do you mean literally, there's no room on the Overlay? Because it looks like the function still works if you look at the logs:

```[05:33:35] Q: Matched [Duty Roulette: Level 50/60 Dungeons]
[05:33:39] Q: Matching State Updated [The Fractal Continuum, 3, 0/1, 1/1, 1/2]
[05:33:45] Q: Matching State Updated [The Fractal Continuum, 3, 0/1, 1/1, 2/2]
[05:33:47] Q: Matching State Updated [The Fractal Continuum, 4, 1/1, 1/1, 2/2]
[05:33:47] Q: Entered Instance Area
```
