### ISSUE TITLE
Name of exact duty is not shown in the Overlay

### ISSUE THREAD

**Issue by Aida-Enna** [devunt/DFAssist#96]
As noted in #90, it was remarked that there's "no more space to place an option" - Does this mean literally, there's no room on the Overlay? Because it looks like the function still works if you look at the logs:

```[05:33:35] Q: Matched [Duty Roulette: Level 50/60 Dungeons]
[05:33:39] Q: Matching State Updated [The Fractal Continuum, 3, 0/1, 1/1, 1/2]
[05:33:45] Q: Matching State Updated [The Fractal Continuum, 3, 0/1, 1/1, 2/2]
[05:33:47] Q: Matching State Updated [The Fractal Continuum, 4, 1/1, 1/1, 2/2]
[05:33:47] Q: Entered Instance Area
```

Perhaps an option to replace the Roulette name with the exact Dungeon name once it pops and begins flashing red? There appears to be room on the Basic Settings for an additional option or two.

EDIT: I see now that it appears it was disabled due to abuse?
```                // CheatRoulette = iniFile.ReadValue("misc", "cheatroulette") == "1";
                CheatRoulette = false; // 악용 방지를 위한 강제 비활성화
```
Could this be re-enabled, perhaps as an option? If not, I'll respect your wishes and keep it disabled.

**Comment by SonicAngel** [comment]
I had asked the same, and got a responce to use this forked project for it
http://www.inven.co.kr/board/ff14/4336/561661
Works just fine. It has not however up to this moment been updated with the 2 new duties of 4.1. I am not aware wether i'll have to re-download it or not, but since its only 1 dung and 1 trial, you can tell what it is.

**Comment by Aida-Enna** [comment]
That's a shame - I've re-enabled that feature (and have updated the english data and added other things/fixed things) in my fork (https://github.com/Aida-Enna/DFAssist) if you'd like to use that.

**Comment by SonicAngel** [comment]
Amazing job Aida! Dont even have the annoying double confirmation for the exact duty but it's ticked by default! Love it :)
Does it autoupdate when you add new info?

**Comment by Aida-Enna** [comment]
Yep! \ o / And thanks, glad you like it ^^

**Comment by lanceangel** [comment]
Aida-Enna, where can we download your .exe?

**Comment by Aida-Enna** [comment]
https://github.com/Aida-Enna/DFAssist/releases
